-- ============================================================
-- Hospital de Galdakao · Guardias de Urología · Fase 1
-- Migración ya aplicada al proyecto Supabase: rxyitbhzzriwecjgqqrg
-- ============================================================
--
-- Tablas:
--   guardias_profiles           — perfiles de usuario (admin/gestor/medico)
--   guardias_doctor_profiles    — perfil extendido del médico
--   guardias_shift_counters     — contadores anuales de guardias por médico
--   guardias_holidays           — festivos (nacional/euskadi/bizkaia/galdakao/especial)
--   guardias_special_days       — días especiales manuales (puentes, etc.)
--   guardias_penosidad_config   — jerarquía de penosidad reordenable
--
-- Vista:
--   guardias_day_classifications — clasificación automática de días 2025-2027
--
-- Seed:
--   • Penosidad por defecto (7 tipos, nivel 1-7)
--   • Festivos nacionales, de Euskadi y de Galdakao para 2025 y 2026
-- ============================================================
-- Ver el SQL completo en el historial de migraciones de Supabase.
