import { Utensils, Dumbbell, ShoppingBag, Stethoscope, Smartphone, Coffee, Building2, Sparkles, type LucideIcon } from "lucide-react";

export interface CaseStudyItem {
  Icon: LucideIcon;
  sector: string;
  platform: string;
  name: string;
  location: string;
  challenge: string;
  solution: string;
  result: string;
  quote: string;
  quoteName: string;
  stats: { label: string; value: string }[];
  color: string;
  accent: string;
}

const CASE_STUDIES: Record<string, CaseStudyItem[]> = {
  es: [
    {
      Icon: Utensils, color: "from-orange-50 to-amber-50", accent: "text-orange-600",
      sector: "Restauración", platform: "Google Maps",
      name: "Pizzería Napoli", location: "Sevilla",
      challenge: "Llevaban 2 años con solo 23 reseñas en Google Maps. La mayoría habían llegado en momentos de queja, lo que hacía que su media fuera de 3.8★ y que no apareciesen en las búsquedas locales.",
      solution: "Implementaron ResenasYa para enviar un WhatsApp automático a cada cliente 30 minutos después de pagar. La IA filtraba las respuestas: los satisfechos recibían el enlace directo a Google Maps, los insatisfechos una respuesta empática para gestionar el problema en privado.",
      result: "En 2 meses pasaron de 23 a 97 reseñas, con una media de 4.7★. Aparecieron en el top 3 de restaurantes italianos en Sevilla y llenaron la lista de espera los fines de semana por primera vez en su historia.",
      quote: "Antes nadie dejaba reseñas aunque estuvieran contentos. Ahora nos llegan solos. Ha cambiado por completo cómo nos ven en Google.",
      quoteName: "Giuseppe M., propietario",
      stats: [{ label: "Reseñas nuevas", value: "+74" }, { label: "Media Google", value: "4.7★" }, { label: "Tiempo", value: "2 meses" }],
    },
    {
      Icon: Dumbbell, color: "from-blue-50 to-indigo-50", accent: "text-blue-600",
      sector: "Fitness", platform: "Google Maps + Incentivo",
      name: "FitBody Gym", location: "Valencia",
      challenge: "Con 58 reseñas en 4 años y un NPS de 72, los socios estaban muy satisfechos pero nadie dejaba valoraciones. El equipo había probado pedir reseñas en persona, pero era incómodo y poco escalable.",
      solution: "Activaron el plan Pro con incentivos: cualquier socio que dejara una reseña de 5★ y enviara la captura de pantalla recibía un 10% de descuento en la siguiente cuota. La IA verificaba automáticamente las 5 estrellas en la captura y enviaba el código al instante.",
      result: "En solo 6 semanas consiguieron 134 reseñas nuevas con una media de 4.9★. El 62% de los socios que recibieron el WhatsApp con incentivo acabaron dejando la reseña y reclamando su descuento.",
      quote: "El sistema de incentivos fue una revelación. Los socios lo veían como un win-win: dejaban una reseña honesta y se llevaban un descuento real. Sin fricciones.",
      quoteName: "Laura P., directora",
      stats: [{ label: "Reseñas nuevas", value: "+134" }, { label: "Media Google", value: "4.9★" }, { label: "Conversión incentivo", value: "62%" }],
    },
    {
      Icon: ShoppingBag, color: "from-green-50 to-emerald-50", accent: "text-green-600",
      sector: "E-commerce", platform: "Trustpilot",
      name: "ModaTrend", location: "Barcelona",
      challenge: "Alta satisfacción de clientes (NPS 78) pero cero presencia en Trustpilot, donde sus potenciales compradores tomaban la decisión final de compra. Sus competidores tenían cientos de valoraciones y ellos solo 12.",
      solution: "Configuraron un WhatsApp automático 48 horas después de la entrega del pedido, cuando el cliente ya había tenido tiempo de probar el producto. El enlace apuntaba directamente a su perfil de Trustpilot.",
      result: "En 4 meses acumularon 289 valoraciones con 4.7★ en Trustpilot. La tasa de conversión de su tienda online subió un 22% al mostrar el widget de Trustpilot en las páginas de producto.",
      quote: "El impacto en conversión fue inmediato. Cuando los visitantes ven 289 reseñas reales de 4.7★, la decisión de compra se toma sola.",
      quoteName: "Marta S., directora de marketing",
      stats: [{ label: "Reseñas Trustpilot", value: "289" }, { label: "Media", value: "4.7★" }, { label: "Conversión web", value: "+22%" }],
    },
    {
      Icon: Stethoscope, color: "from-purple-50 to-violet-50", accent: "text-purple-600",
      sector: "Salud", platform: "Google Maps",
      name: "Clínica Dental Ortiz", location: "Zaragoza",
      challenge: "Sector con alta sensibilidad: necesitaban captar opiniones positivas de forma natural, pero les preocupaba que los casos complicados acabaran en reseñas negativas públicas que dañaran su reputación.",
      solution: "El filtro de sentimiento de la IA fue la clave. Solo los pacientes con respuestas claramente positivas recibían el enlace a Google Maps. Los que expresaban incomodidad recibían un mensaje empático invitándoles a llamar directamente.",
      result: "62 reseñas nuevas en 4 meses, todas por encima de 4 estrellas. Ninguna respuesta negativa llegó a publicarse: todas se gestionaron en privado.",
      quote: "Lo que más valoramos no son las reseñas nuevas, sino que ninguna negativa ha llegado a publicarse. Gestionamos los casos delicados antes de que se conviertan en un problema.",
      quoteName: "Dr. Ortiz, propietario",
      stats: [{ label: "Reseñas nuevas", value: "+62" }, { label: "Reseñas negativas públicas", value: "0" }, { label: "Satisfacción", value: "94%" }],
    },
    {
      Icon: Smartphone, color: "from-rose-50 to-pink-50", accent: "text-rose-600",
      sector: "App móvil", platform: "App Store + Play Store",
      name: "RecetApp", location: "Madrid",
      challenge: "18.000 usuarios activos mensuales pero solo 312 valoraciones en total. El ratio bajo lastraba su posición en el ranking de la categoría y frenaba las descargas orgánicas.",
      solution: "Segmentaron sus usuarios por dispositivo: los de iOS recibían el WhatsApp con el enlace de App Store, los de Android con el de Play Store. El mensaje se enviaba a usuarios que habían abierto la app al menos 5 veces en el último mes.",
      result: "En 3 meses consiguieron +520 valoraciones. Su posición en el ranking de Gastronomía pasó del top 40 al top 10, con un incremento del 35% en descargas orgánicas.",
      quote: "El truco de segmentar por dispositivo fue brillante. Cada usuario recibía exactamente el enlace que le correspondía. La tasa de respuesta fue del 28%.",
      quoteName: "Álvaro R., founder",
      stats: [{ label: "Valoraciones nuevas", value: "+520" }, { label: "Plataformas", value: "2" }, { label: "Posición ranking", value: "Top 10" }],
    },
    {
      Icon: Coffee, color: "from-yellow-50 to-orange-50", accent: "text-yellow-700",
      sector: "Cafetería", platform: "Google Maps + Incentivo",
      name: "Bloom Coffee", location: "Zaragoza",
      challenge: "31 reseñas y 4.2★ mientras la competencia de enfrente tenía 180 reseñas y 4.8★. Siempre aparecían segundos. Los clientes habituales los adoraban pero nunca lo ponían en Google.",
      solution: "Lanzaron el incentivo definitivo: deja una reseña de 5★, envía la captura y te invitamos a un café. La IA verificaba automáticamente las 5 estrellas y enviaba el mensaje de confirmación al instante.",
      result: "De 31 a 97 reseñas en 3 semanas y media de 4.8★. Superaron a la competencia y pasaron a aparecer primeros en búsquedas como 'cafetería Zaragoza centro'.",
      quote: "En 3 semanas teníamos más reseñas que la competencia que llevaba años. Y lo mejor: el café de cortesía nos costaba 30 céntimos y nos traía nuevos clientes.",
      quoteName: "Ana C., propietaria",
      stats: [{ label: "Reseñas nuevas", value: "+66" }, { label: "Media Google", value: "4.8★" }, { label: "Tiempo", value: "3 semanas" }],
    },
    {
      Icon: Building2, color: "from-teal-50 to-cyan-50", accent: "text-teal-600",
      sector: "Hostelería", platform: "Google Business Profile",
      name: "Hotel Mirador", location: "Málaga",
      challenge: "Con 4.2★ y varias reseñas de 1 estrella sin texto ni historial de usuario, sospechaban que eran falsas de un competidor. Esas 4 reseñas les estaban hundiendo la media y haciéndoles perder reservas directas.",
      solution: "Con la integración de Google Business Profile de ResenasYa, el sistema analizó automáticamente sus reseñas negativas e identificó 4 que incumplían las políticas de Google: sin comentario, perfiles sin historial y contenido genérico. Solicitaron la eliminación con un clic.",
      result: "Google eliminó 3 de las 4 reseñas en 12 días. Su media pasó de 4.2★ a 4.6★ y recuperaron 3 posiciones en el ranking de hoteles de su zona. Las reservas directas aumentaron un 18% ese trimestre.",
      quote: "Llevábamos meses viendo cómo esas reseñas injustas nos hundían. En 12 días Google eliminó 3 de 4. Ha sido un cambio brutal para nuestra reputación.",
      quoteName: "Carlos V., director",
      stats: [{ label: "Reseñas eliminadas", value: "3 de 4" }, { label: "Media Google", value: "4.6★" }, { label: "Reservas directas", value: "+18%" }],
    },
    {
      Icon: Sparkles, color: "from-violet-50 to-purple-50", accent: "text-violet-600",
      sector: "Bienestar", platform: "Google Business Profile",
      name: "Spa Serenity", location: "Bilbao",
      challenge: "Recibían 15 reseñas nuevas por semana en Google Maps pero solo respondían al 8%: no había tiempo. Google penaliza los perfiles que no responden y ellos lo notaban en el ranking.",
      solution: "Conectaron Google Business Profile con ResenasYa. La IA genera respuestas personalizadas para cada reseña teniendo en cuenta el comentario específico del cliente y el tono del negocio. Las respuestas se publican automáticamente en menos de una hora.",
      result: "En 2 meses pasaron del 8% al 94% de respuestas. Google los marcó como 'Responde habitualmente' en su ficha. Subieron 4 posiciones en búsquedas de 'spa Bilbao' y el número de clics en su perfil aumentó un 31%.",
      quote: "Antes tardábamos días en responder y muchas se quedaban sin respuesta. Ahora todas tienen una respuesta personalizada en menos de una hora. Los clientes lo notan y lo agradecen.",
      quoteName: "Elena R., directora",
      stats: [{ label: "Tasa de respuesta", value: "94%" }, { label: "Tiempo de respuesta", value: "<1 hora" }, { label: "Clics en perfil", value: "+31%" }],
    },
  ],

  en: [
    {
      Icon: Utensils, color: "from-orange-50 to-amber-50", accent: "text-orange-600",
      sector: "Restaurant", platform: "Google Maps",
      name: "Tony's Trattoria", location: "New York",
      challenge: "23 reviews in 2 years. Only complaints came in — happy customers never bothered to write one. Their 3.8★ average kept them invisible in local searches.",
      solution: "They set up ResenasYa to send an automatic WhatsApp 30 minutes after payment. The AI filtered responses: satisfied customers got the direct Google Maps link, unhappy ones got an empathetic reply to resolve the issue privately.",
      result: "In 2 months they went from 23 to 97 reviews with a 4.7★ average. They ranked in the top 3 Italian restaurants in their area and had a waiting list on weekends for the first time.",
      quote: "Nobody used to leave reviews even when they were happy. Now they come on their own. It's completely changed how people see us on Google.",
      quoteName: "Giuseppe M., owner",
      stats: [{ label: "New reviews", value: "+74" }, { label: "Google rating", value: "4.7★" }, { label: "Time", value: "2 months" }],
    },
    {
      Icon: Dumbbell, color: "from-blue-50 to-indigo-50", accent: "text-blue-600",
      sector: "Fitness", platform: "Google Maps + Incentive",
      name: "IronCore Gym", location: "Chicago",
      challenge: "58 reviews in 4 years with an NPS of 72. Members were very satisfied but nobody left ratings. The team had tried asking in person, but it felt awkward and didn't scale.",
      solution: "They activated the Pro plan with incentives: any member who left a 5★ review and sent the screenshot received 10% off their next month. The AI automatically verified the 5 stars and sent the discount code instantly.",
      result: "In just 6 weeks they got 134 new reviews with a 4.9★ average. 62% of members who received the incentive WhatsApp ended up leaving a review and claiming their discount.",
      quote: "The incentive system was a revelation. Members saw it as a win-win: they left an honest review and got a real discount. No friction whatsoever.",
      quoteName: "Laura P., director",
      stats: [{ label: "New reviews", value: "+134" }, { label: "Google rating", value: "4.9★" }, { label: "Incentive conversion", value: "62%" }],
    },
    {
      Icon: ShoppingBag, color: "from-green-50 to-emerald-50", accent: "text-green-600",
      sector: "E-commerce", platform: "Trustpilot",
      name: "StyleNest", location: "Los Angeles",
      challenge: "High customer satisfaction (NPS 78) but zero Trustpilot presence — that's where buyers made their final purchase decision. Competitors had hundreds of reviews; they had just 12.",
      solution: "They set up an automated WhatsApp 48 hours after delivery, when the customer had already had time to try the product. The link pointed directly to their Trustpilot profile.",
      result: "In 4 months they accumulated 289 reviews with 4.7★ on Trustpilot. Their online store conversion rate went up 22% after displaying the Trustpilot widget on product pages.",
      quote: "The conversion impact was immediate. When visitors see 289 real 4.7★ reviews, the purchase decision makes itself.",
      quoteName: "Marta S., marketing director",
      stats: [{ label: "Trustpilot reviews", value: "289" }, { label: "Rating", value: "4.7★" }, { label: "Web conversion", value: "+22%" }],
    },
    {
      Icon: Stethoscope, color: "from-purple-50 to-violet-50", accent: "text-purple-600",
      sector: "Healthcare", platform: "Google Maps",
      name: "Bright Smile Dental", location: "Austin",
      challenge: "Sensitive sector: they needed to collect positive opinions naturally, but worried that difficult cases would end up as public negative reviews damaging their reputation.",
      solution: "The AI sentiment filter was the key. Only patients with clearly positive responses received the Google Maps link. Those expressing discomfort received an empathetic message inviting them to call directly.",
      result: "62 new reviews in 4 months, all above 4 stars. No negative response made it public — all were handled privately.",
      quote: "What we value most isn't the new reviews, but that no negative one has been published. We handle sensitive cases before they become a problem.",
      quoteName: "Dr. Smith, owner",
      stats: [{ label: "New reviews", value: "+62" }, { label: "Public negative reviews", value: "0" }, { label: "Satisfaction", value: "94%" }],
    },
    {
      Icon: Smartphone, color: "from-rose-50 to-pink-50", accent: "text-rose-600",
      sector: "Mobile app", platform: "App Store + Play Store",
      name: "FoodieApp", location: "San Francisco",
      challenge: "18,000 monthly active users but only 312 ratings total across both stores. The low ratio was hurting their category ranking and slowing organic downloads.",
      solution: "They segmented users by device: iOS users got the App Store link, Android users got Play Store. The message was sent to users who had opened the app at least 5 times in the past month.",
      result: "In 3 months they got +520 ratings across both platforms. Their ranking in the Food category went from top 40 to top 10, with a 35% increase in organic downloads.",
      quote: "Segmenting by device was brilliant. Each user got exactly the right link. The response rate was 28% — way better than any in-app pop-up.",
      quoteName: "Alex R., founder",
      stats: [{ label: "New ratings", value: "+520" }, { label: "Platforms", value: "2" }, { label: "Ranking position", value: "Top 10" }],
    },
    {
      Icon: Coffee, color: "from-yellow-50 to-orange-50", accent: "text-yellow-700",
      sector: "Café", platform: "Google Maps + Incentive",
      name: "Morning Bloom Café", location: "Portland",
      challenge: "31 reviews and 4.2★ while the café across the street had 180 reviews and 4.8★, always appearing first. Regulars loved them but never put it on Google.",
      solution: "They launched the ultimate incentive: leave a 5★ review, send the screenshot and we'll buy you a coffee. The AI automatically verified the 5 stars and sent the confirmation message instantly.",
      result: "From 31 to 97 reviews in 3 weeks with a 4.8★ average. They overtook the competition and started appearing first for searches like 'café Portland downtown'.",
      quote: "In 3 weeks we had more reviews than our competitor who'd been there for years. The best part: the free coffee cost us 50 cents and brought new customers via Google.",
      quoteName: "Anna C., owner",
      stats: [{ label: "New reviews", value: "+66" }, { label: "Google rating", value: "4.8★" }, { label: "Time", value: "3 weeks" }],
    },
    {
      Icon: Building2, color: "from-teal-50 to-cyan-50", accent: "text-teal-600",
      sector: "Hospitality", platform: "Google Business Profile",
      name: "The Viewpoint Hotel", location: "Miami",
      challenge: "With a 4.2★ average and several 1-star reviews with no text or user history, they suspected fake reviews from a competitor. Those 4 reviews were dragging down their score and costing them direct bookings.",
      solution: "Using ResenasYa's Google Business Profile integration, the system automatically analysed their negative reviews and flagged 4 that violated Google's policies: no comment, no user history, and generic content. They requested removal in one click.",
      result: "Google removed 3 of the 4 reviews within 12 days. Their average went from 4.2★ to 4.6★ and they climbed 3 positions in the local hotel ranking. Direct bookings increased 18% that quarter.",
      quote: "We'd been watching those unfair reviews drag us down for months. In 12 days Google removed 3 of 4. It's been a massive change for our reputation.",
      quoteName: "Carlos V., manager",
      stats: [{ label: "Reviews removed", value: "3 of 4" }, { label: "Google rating", value: "4.6★" }, { label: "Direct bookings", value: "+18%" }],
    },
    {
      Icon: Sparkles, color: "from-violet-50 to-purple-50", accent: "text-violet-600",
      sector: "Wellness", platform: "Google Business Profile",
      name: "Serenity Spa", location: "Austin",
      challenge: "They received 15 new Google Maps reviews per week but only replied to 8% — there was never enough time. Google penalises profiles that don't respond and they were feeling it in the rankings.",
      solution: "They connected Google Business Profile with ResenasYa. The AI generates a personalised reply for every review, taking into account the customer's specific comment and the business tone. Responses are published automatically within an hour.",
      result: "In 2 months their response rate went from 8% to 94%. Google labelled them as 'Usually responds' on their listing. They climbed 4 positions in 'spa Austin' searches and profile clicks increased 31%.",
      quote: "We used to take days to reply and many reviews got no response at all. Now every one has a personalised reply within an hour. Customers notice and appreciate it.",
      quoteName: "Elena R., director",
      stats: [{ label: "Response rate", value: "94%" }, { label: "Response time", value: "<1 hour" }, { label: "Profile clicks", value: "+31%" }],
    },
  ],

  fr: [
    {
      Icon: Utensils, color: "from-orange-50 to-amber-50", accent: "text-orange-600",
      sector: "Restauration", platform: "Google Maps",
      name: "Pizzeria Bella Napoli", location: "Paris",
      challenge: "23 avis en 2 ans. Seuls les mécontents prenaient la peine d'écrire. Leur moyenne de 3,8★ les rendait invisibles dans les recherches locales.",
      solution: "Ils ont mis en place ResenasYa pour envoyer un WhatsApp automatique 30 minutes après le paiement. L'IA filtrait les réponses : les clients satisfaits recevaient le lien Google Maps, les insatisfaits une réponse empathique pour gérer le problème en privé.",
      result: "En 2 mois, ils sont passés de 23 à 97 avis avec une moyenne de 4,7★. Ils sont apparus dans le top 3 des restaurants italiens à Paris et ont rempli leur liste d'attente les week-ends.",
      quote: "Personne ne laissait d'avis même content. Maintenant ils arrivent seuls. Ça a complètement changé notre image sur Google.",
      quoteName: "Giuseppe M., propriétaire",
      stats: [{ label: "Nouveaux avis", value: "+74" }, { label: "Note Google", value: "4,7★" }, { label: "Durée", value: "2 mois" }],
    },
    {
      Icon: Dumbbell, color: "from-blue-50 to-indigo-50", accent: "text-blue-600",
      sector: "Fitness", platform: "Google Maps + Incentive",
      name: "FitZone Gym", location: "Lyon",
      challenge: "58 avis en 4 ans avec un NPS de 72. Les membres étaient très satisfaits mais personne ne laissait de note. Demander en personne était gênant et peu scalable.",
      solution: "Ils ont activé le plan Pro avec incentives : tout membre laissant un avis 5★ et envoyant la capture recevait 10% de réduction sur le mois suivant. L'IA vérifiait automatiquement et envoyait le code instantanément.",
      result: "En seulement 6 semaines, 134 nouveaux avis avec une moyenne de 4,9★. 62% des membres ayant reçu le WhatsApp avec incentive ont laissé leur avis.",
      quote: "Le système d'incentives a été une révélation. Les membres y voyaient un win-win : ils laissaient un avis honnête et obtenaient une vraie réduction. Sans friction.",
      quoteName: "Laura P., directrice",
      stats: [{ label: "Nouveaux avis", value: "+134" }, { label: "Note Google", value: "4,9★" }, { label: "Conv. incentive", value: "62%" }],
    },
    {
      Icon: ShoppingBag, color: "from-green-50 to-emerald-50", accent: "text-green-600",
      sector: "E-commerce", platform: "Trustpilot",
      name: "ModeParis", location: "Bordeaux",
      challenge: "Forte satisfaction client (NPS 78) mais zéro présence sur Trustpilot — là où les acheteurs prenaient leur décision finale. Les concurrents avaient des centaines d'avis, eux seulement 12.",
      solution: "Ils ont configuré un WhatsApp automatique 48h après la livraison. Le lien pointait directement vers leur profil Trustpilot.",
      result: "En 4 mois, 289 avis avec 4,7★ sur Trustpilot. Le taux de conversion de leur boutique a augmenté de 22% après l'affichage du widget Trustpilot.",
      quote: "L'impact sur la conversion a été immédiat. Quand les visiteurs voient 289 vrais avis à 4,7★, la décision d'achat se prend toute seule.",
      quoteName: "Marta S., directrice marketing",
      stats: [{ label: "Avis Trustpilot", value: "289" }, { label: "Note", value: "4,7★" }, { label: "Conversion web", value: "+22%" }],
    },
    {
      Icon: Stethoscope, color: "from-purple-50 to-violet-50", accent: "text-purple-600",
      sector: "Santé", platform: "Google Maps",
      name: "Cabinet Dentaire Duval", location: "Marseille",
      challenge: "Secteur sensible : ils devaient recueillir des avis positifs naturellement, mais craignaient que les cas difficiles finissent en avis négatifs publics.",
      solution: "Le filtre de sentiment IA a été la clé. Seuls les patients avec des réponses clairement positives recevaient le lien Google Maps. Les autres recevaient un message empathique pour appeler directement.",
      result: "62 nouveaux avis en 4 mois, tous au-dessus de 4 étoiles. Aucun avis négatif n'a été publié : tous gérés en privé.",
      quote: "Ce qu'on valorise le plus, c'est qu'aucun avis négatif n'a été publié. On gère les cas délicats avant qu'ils deviennent un problème.",
      quoteName: "Dr. Duval, propriétaire",
      stats: [{ label: "Nouveaux avis", value: "+62" }, { label: "Avis négatifs publics", value: "0" }, { label: "Satisfaction", value: "94%" }],
    },
    {
      Icon: Smartphone, color: "from-rose-50 to-pink-50", accent: "text-rose-600",
      sector: "Application mobile", platform: "App Store + Play Store",
      name: "RecetteApp", location: "Toulouse",
      challenge: "18 000 utilisateurs actifs mais seulement 312 notes au total. Ce faible ratio pénalisait leur classement et freinait les téléchargements organiques.",
      solution: "Ils ont segmenté par appareil : iOS recevait le lien App Store, Android le lien Play Store. Le message était envoyé aux utilisateurs ayant ouvert l'app au moins 5 fois dans le mois.",
      result: "En 3 mois, +520 notes sur les deux plateformes. Leur position dans la catégorie Gastronomie est passée du top 40 au top 10, avec 35% de téléchargements organiques en plus.",
      quote: "Segmenter par appareil était brillant. Chaque utilisateur recevait exactement le bon lien. Le taux de réponse était de 28%.",
      quoteName: "Alexis R., fondateur",
      stats: [{ label: "Nouvelles notes", value: "+520" }, { label: "Plateformes", value: "2" }, { label: "Position", value: "Top 10" }],
    },
    {
      Icon: Coffee, color: "from-yellow-50 to-orange-50", accent: "text-yellow-700",
      sector: "Café", platform: "Google Maps + Incentive",
      name: "Café des Fleurs", location: "Nantes",
      challenge: "31 avis et 4,2★ alors que le concurrent d'en face avait 180 avis et 4,8★. Toujours en deuxième position. Les habitués les adoraient mais ne le disaient jamais sur Google.",
      solution: "Ils ont lancé l'incentive ultime : laissez un avis 5★, envoyez la capture et on vous offre un café. L'IA vérifiait automatiquement et envoyait la confirmation instantanément.",
      result: "De 31 à 97 avis en 3 semaines et 4,8★. Ils ont dépassé la concurrence et apparaissent maintenant premiers pour 'café Nantes centre'.",
      quote: "En 3 semaines on avait plus d'avis que le concurrent qui était là depuis des années. Et le café offert ne coûtait que 50 centimes.",
      quoteName: "Anne C., propriétaire",
      stats: [{ label: "Nouveaux avis", value: "+66" }, { label: "Note Google", value: "4,8★" }, { label: "Durée", value: "3 semaines" }],
    },
    {
      Icon: Building2, color: "from-teal-50 to-cyan-50", accent: "text-teal-600",
      sector: "Hôtellerie", platform: "Google Business Profile",
      name: "Hôtel Belvédère", location: "Nice",
      challenge: "Avec une moyenne de 4,2★ et plusieurs avis 1 étoile sans texte ni historique utilisateur, ils soupçonnaient des faux avis d'un concurrent. Ces 4 avis faisaient chuter leur note et leur coûtaient des réservations directes.",
      solution: "Grâce à l'intégration Google Business Profile de ResenasYa, le système a analysé automatiquement leurs avis négatifs et identifié 4 qui enfreignaient les politiques de Google : sans commentaire, profils sans historique et contenu générique. Ils ont demandé la suppression en un clic.",
      result: "Google a supprimé 3 des 4 avis en 12 jours. Leur moyenne est passée de 4,2★ à 4,6★ et ils ont récupéré 3 positions dans le classement local des hôtels. Les réservations directes ont augmenté de 18% ce trimestre.",
      quote: "Ça faisait des mois qu'on voyait ces avis injustes nous plomber. En 12 jours Google en a supprimé 3 sur 4. Ça a été un changement énorme pour notre réputation.",
      quoteName: "Carlos V., directeur",
      stats: [{ label: "Avis supprimés", value: "3 sur 4" }, { label: "Note Google", value: "4,6★" }, { label: "Réservations directes", value: "+18%" }],
    },
    {
      Icon: Sparkles, color: "from-violet-50 to-purple-50", accent: "text-violet-600",
      sector: "Bien-être", platform: "Google Business Profile",
      name: "Spa Sérénité", location: "Bordeaux",
      challenge: "Ils recevaient 15 nouveaux avis par semaine sur Google Maps mais n'en répondaient qu'à 8% : faute de temps. Google pénalise les profils qui ne répondent pas et ils le ressentaient dans leur classement.",
      solution: "Ils ont connecté Google Business Profile à ResenasYa. L'IA génère des réponses personnalisées pour chaque avis en tenant compte du commentaire spécifique du client et du ton du commerce. Les réponses sont publiées automatiquement en moins d'une heure.",
      result: "En 2 mois, leur taux de réponse est passé de 8% à 94%. Google les a labellisés 'Répond généralement' sur leur fiche. Ils ont gagné 4 positions dans les recherches 'spa Bordeaux' et les clics sur leur profil ont augmenté de 31%.",
      quote: "Avant on mettait des jours à répondre et beaucoup restaient sans réponse. Maintenant chaque avis a une réponse personnalisée en moins d'une heure. Les clients le remarquent et l'apprécient.",
      quoteName: "Elena R., directrice",
      stats: [{ label: "Taux de réponse", value: "94%" }, { label: "Temps de réponse", value: "<1 heure" }, { label: "Clics sur profil", value: "+31%" }],
    },
  ],

  de: [
    {
      Icon: Utensils, color: "from-orange-50 to-amber-50", accent: "text-orange-600",
      sector: "Restaurant", platform: "Google Maps",
      name: "Trattoria Bella Italia", location: "Berlin",
      challenge: "23 Bewertungen in 2 Jahren. Nur Unzufriedene schrieben — zufriedene Kunden schwiegen. Der Durchschnitt von 3,8★ machte sie in der lokalen Suche unsichtbar.",
      solution: "Sie richteten ResenasYa ein, um 30 Minuten nach der Zahlung eine automatische WhatsApp zu senden. Die KI filterte Antworten: Zufriedene erhielten den Google Maps-Link, Unzufriedene eine empathische Antwort.",
      result: "In 2 Monaten stiegen sie von 23 auf 97 Bewertungen mit einem Durchschnitt von 4,7★. Sie erschienen unter den Top 3 in der Umgebung und hatten erstmals eine Warteliste am Wochenende.",
      quote: "Früher hinterließen Kunden nie Bewertungen, auch wenn sie zufrieden waren. Jetzt kommen sie von selbst. Es hat komplett verändert, wie man uns auf Google sieht.",
      quoteName: "Giuseppe M., Inhaber",
      stats: [{ label: "Neue Bewertungen", value: "+74" }, { label: "Google-Bewertung", value: "4,7★" }, { label: "Zeitraum", value: "2 Monate" }],
    },
    {
      Icon: Dumbbell, color: "from-blue-50 to-indigo-50", accent: "text-blue-600",
      sector: "Fitness", platform: "Google Maps + Anreiz",
      name: "FitPower Gym", location: "München",
      challenge: "58 Bewertungen in 4 Jahren bei einem NPS von 72. Die Mitglieder waren zufrieden, aber niemand hinterließ Bewertungen. Persönlich danach zu fragen war unangenehm und nicht skalierbar.",
      solution: "Sie aktivierten den Pro-Plan mit Anreizen: Jedes Mitglied, das eine 5★-Bewertung hinterließ und den Screenshot schickte, erhielt 10% Rabatt auf den nächsten Monat. Die KI prüfte automatisch und schickte den Code sofort.",
      result: "In nur 6 Wochen erzielten sie 134 neue Bewertungen mit einem Durchschnitt von 4,9★. 62% der Mitglieder, die den Anreiz-WhatsApp erhielten, hinterließen eine Bewertung.",
      quote: "Das Anreizsystem war eine Offenbarung. Die Mitglieder sahen es als Win-Win: ehrliche Bewertung gegen echten Rabatt. Ohne Reibung.",
      quoteName: "Laura P., Leiterin",
      stats: [{ label: "Neue Bewertungen", value: "+134" }, { label: "Google-Bewertung", value: "4,9★" }, { label: "Anreiz-Conversion", value: "62%" }],
    },
    {
      Icon: ShoppingBag, color: "from-green-50 to-emerald-50", accent: "text-green-600",
      sector: "E-Commerce", platform: "Trustpilot",
      name: "ModeTrend", location: "Hamburg",
      challenge: "Hohe Kundenzufriedenheit (NPS 78), aber null Trustpilot-Präsenz — dort trafen Käufer ihre endgültige Kaufentscheidung. Wettbewerber hatten Hunderte von Bewertungen, sie nur 12.",
      solution: "Sie richteten 48 Stunden nach der Lieferung eine automatische WhatsApp ein. Der Link zeigte direkt auf ihr Trustpilot-Profil.",
      result: "In 4 Monaten sammelten sie 289 Bewertungen mit 4,7★ auf Trustpilot. Die Conversion-Rate ihres Online-Shops stieg um 22%.",
      quote: "Der Einfluss auf die Conversion war sofort spürbar. Wenn Besucher 289 echte 4,7★-Bewertungen sehen, trifft sich die Kaufentscheidung von selbst.",
      quoteName: "Marta S., Marketingleiterin",
      stats: [{ label: "Trustpilot-Bewertungen", value: "289" }, { label: "Bewertung", value: "4,7★" }, { label: "Web-Conversion", value: "+22%" }],
    },
    {
      Icon: Stethoscope, color: "from-purple-50 to-violet-50", accent: "text-purple-600",
      sector: "Gesundheit", platform: "Google Maps",
      name: "Zahnarztpraxis Müller", location: "Frankfurt",
      challenge: "Sensibles Umfeld: Sie wollten positive Meinungen natürlich sammeln, fürchteten aber, dass schwierige Fälle in negativen öffentlichen Bewertungen enden.",
      solution: "Der KI-Sentiment-Filter war entscheidend. Nur Patienten mit klar positiven Antworten erhielten den Google Maps-Link. Andere erhielten eine empathische Nachricht mit der Bitte anzurufen.",
      result: "62 neue Bewertungen in 4 Monaten, alle über 4 Sterne. Keine negative Bewertung wurde veröffentlicht — alle privat behandelt.",
      quote: "Was uns am meisten wertvoll ist, sind nicht die neuen Bewertungen, sondern dass keine negative veröffentlicht wurde.",
      quoteName: "Dr. Müller, Inhaber",
      stats: [{ label: "Neue Bewertungen", value: "+62" }, { label: "Öffentl. neg. Bewertungen", value: "0" }, { label: "Zufriedenheit", value: "94%" }],
    },
    {
      Icon: Smartphone, color: "from-rose-50 to-pink-50", accent: "text-rose-600",
      sector: "Mobile App", platform: "App Store + Play Store",
      name: "RezeptApp", location: "Köln",
      challenge: "18.000 aktive Nutzer monatlich, aber nur 312 Bewertungen insgesamt. Das niedrige Verhältnis schadete dem Ranking und verlangsamte organische Downloads.",
      solution: "Sie segmentierten nach Gerät: iOS-Nutzer erhielten den App Store-Link, Android-Nutzer den Play Store-Link. Die Nachricht wurde an Nutzer geschickt, die die App mindestens 5 Mal im letzten Monat geöffnet hatten.",
      result: "In 3 Monaten +520 Bewertungen auf beiden Plattformen. Ihr Ranking in der Kategorie Gastronomie stieg von Top 40 auf Top 10, mit 35% mehr organischen Downloads.",
      quote: "Die Segmentierung nach Gerät war genial. Jeder Nutzer erhielt genau den richtigen Link. Die Antwortrate lag bei 28%.",
      quoteName: "Alex R., Gründer",
      stats: [{ label: "Neue Bewertungen", value: "+520" }, { label: "Plattformen", value: "2" }, { label: "Position", value: "Top 10" }],
    },
    {
      Icon: Coffee, color: "from-yellow-50 to-orange-50", accent: "text-yellow-700",
      sector: "Café", platform: "Google Maps + Anreiz",
      name: "Café Sonnenschein", location: "Düsseldorf",
      challenge: "31 Bewertungen und 4,2★, während das Café gegenüber 180 Bewertungen und 4,8★ hatte und immer als Erstes bei Google erschien.",
      solution: "Sie starteten den ultimativen Anreiz: 5★-Bewertung hinterlassen, Screenshot schicken, kostenloses Getränk erhalten. Die KI prüfte die 5 Sterne automatisch und schickte sofort die Bestätigung.",
      result: "Von 31 auf 97 Bewertungen in 3 Wochen und 4,8★. Sie überholten die Konkurrenz und erscheinen jetzt als Erste bei Suchen wie 'Café Düsseldorf Innenstadt'.",
      quote: "In 3 Wochen hatten wir mehr Bewertungen als der Konkurrent, der seit Jahren da ist. Das Freigetränk kostete uns 50 Cent und brachte neue Kunden.",
      quoteName: "Anna C., Inhaberin",
      stats: [{ label: "Neue Bewertungen", value: "+66" }, { label: "Google-Bewertung", value: "4,8★" }, { label: "Zeitraum", value: "3 Wochen" }],
    },
    {
      Icon: Building2, color: "from-teal-50 to-cyan-50", accent: "text-teal-600",
      sector: "Gastgewerbe", platform: "Google Business Profile",
      name: "Hotel Aussichtsturm", location: "Heidelberg",
      challenge: "Mit einem Durchschnitt von 4,2★ und mehreren 1-Stern-Bewertungen ohne Text oder Nutzerverlauf vermuteten sie gefälschte Bewertungen eines Konkurrenten. Diese 4 Bewertungen zogen ihren Schnitt nach unten und kosteten sie Direktbuchungen.",
      solution: "Mit der Google Business Profile-Integration von ResenasYa analysierte das System automatisch ihre negativen Bewertungen und identifizierte 4, die gegen Googles Richtlinien verstießen: kein Kommentar, keine Nutzerhistorie, generischer Inhalt. Sie beantragten die Löschung per Klick.",
      result: "Google entfernte 3 der 4 Bewertungen binnen 12 Tagen. Ihr Durchschnitt stieg von 4,2★ auf 4,6★ und sie gewannen 3 Positionen im lokalen Hotel-Ranking zurück. Die Direktbuchungen stiegen in diesem Quartal um 18%.",
      quote: "Monatelang haben wir zugesehen, wie diese ungerechten Bewertungen uns runterzogen. In 12 Tagen hat Google 3 von 4 entfernt. Das war ein riesiger Wandel für unsere Reputation.",
      quoteName: "Carlos V., Direktor",
      stats: [{ label: "Entfernte Bewertungen", value: "3 von 4" }, { label: "Google-Bewertung", value: "4,6★" }, { label: "Direktbuchungen", value: "+18%" }],
    },
    {
      Icon: Sparkles, color: "from-violet-50 to-purple-50", accent: "text-violet-600",
      sector: "Wellness", platform: "Google Business Profile",
      name: "Spa Serenity", location: "Stuttgart",
      challenge: "Sie erhielten 15 neue Google Maps-Bewertungen pro Woche, antworteten aber nur auf 8% — es fehlte schlicht die Zeit. Google bestraft Profile, die nicht antworten, und sie spürten das im Ranking.",
      solution: "Sie verbanden Google Business Profile mit ResenasYa. Die KI generiert personalisierte Antworten für jede Bewertung unter Berücksichtigung des spezifischen Kommentars und des Tonfalls des Unternehmens. Antworten werden automatisch in unter einer Stunde veröffentlicht.",
      result: "In 2 Monaten stieg ihre Antwortrate von 8% auf 94%. Google kennzeichnete sie als 'Antwortet in der Regel' in ihrem Eintrag. Sie kletterten 4 Positionen bei Suchen nach 'Spa Stuttgart' und die Profilklicks stiegen um 31%.",
      quote: "Früher haben wir tagelang gewartet und viele Bewertungen blieben unbeantwortet. Jetzt erhält jede eine persönliche Antwort in unter einer Stunde. Die Kunden bemerken und schätzen das.",
      quoteName: "Elena R., Leiterin",
      stats: [{ label: "Antwortrate", value: "94%" }, { label: "Antwortzeit", value: "<1 Stunde" }, { label: "Profilklicks", value: "+31%" }],
    },
  ],

  it: [
    {
      Icon: Utensils, color: "from-orange-50 to-amber-50", accent: "text-orange-600",
      sector: "Ristorazione", platform: "Google Maps",
      name: "Pizzeria Napoli Vera", location: "Roma",
      challenge: "23 recensioni in 2 anni. Arrivavano solo nei momenti di lamentela. La media di 3,8★ li rendeva invisibili nelle ricerche locali.",
      solution: "Hanno implementato ResenasYa per inviare un WhatsApp automatico 30 minuti dopo il pagamento. L'IA filtrava le risposte: i soddisfatti ricevevano il link a Google Maps, gli insoddisfatti una risposta empatica.",
      result: "In 2 mesi sono passati da 23 a 97 recensioni con una media di 4,7★. Sono apparsi nella top 3 dei ristoranti italiani a Roma e hanno riempito la lista d'attesa nei weekend.",
      quote: "Nessuno lasciava recensioni anche quando era contento. Ora arrivano da soli. Ha cambiato completamente come ci vedono su Google.",
      quoteName: "Giuseppe M., proprietario",
      stats: [{ label: "Nuove recensioni", value: "+74" }, { label: "Media Google", value: "4,7★" }, { label: "Tempo", value: "2 mesi" }],
    },
    {
      Icon: Dumbbell, color: "from-blue-50 to-indigo-50", accent: "text-blue-600",
      sector: "Fitness", platform: "Google Maps + Incentivo",
      name: "FitGym Milano", location: "Milano",
      challenge: "58 recensioni in 4 anni con NPS di 72. I soci erano soddisfatti ma nessuno lasciava valutazioni. Chiedere di persona era imbarazzante e non scalabile.",
      solution: "Hanno attivato il piano Pro con incentivi: ogni socio che lasciava una recensione 5★ e inviava lo screenshot riceveva il 10% di sconto sulla quota successiva. L'IA verificava automaticamente e inviava il codice all'istante.",
      result: "In sole 6 settimane hanno ottenuto 134 nuove recensioni con una media di 4,9★. Il 62% dei soci che hanno ricevuto il WhatsApp con incentivo ha lasciato la recensione.",
      quote: "Il sistema di incentivi è stata una rivelazione. I soci lo vedevano come un win-win: recensione onesta in cambio di uno sconto reale. Senza attrito.",
      quoteName: "Laura P., direttrice",
      stats: [{ label: "Nuove recensioni", value: "+134" }, { label: "Media Google", value: "4,9★" }, { label: "Conv. incentivo", value: "62%" }],
    },
    {
      Icon: ShoppingBag, color: "from-green-50 to-emerald-50", accent: "text-green-600",
      sector: "E-commerce", platform: "Trustpilot",
      name: "ModaItalia", location: "Torino",
      challenge: "Alta soddisfazione (NPS 78) ma zero presenza su Trustpilot — dove i compratori prendevano la decisione finale. I concorrenti avevano centinaia di recensioni, loro solo 12.",
      solution: "Hanno configurato un WhatsApp automatico 48 ore dopo la consegna. Il link puntava direttamente al loro profilo Trustpilot.",
      result: "In 4 mesi hanno accumulato 289 recensioni con 4,7★ su Trustpilot. Il tasso di conversione del loro negozio online è aumentato del 22%.",
      quote: "L'impatto sulla conversione è stato immediato. Quando i visitatori vedono 289 recensioni reali a 4,7★, la decisione d'acquisto si prende da sola.",
      quoteName: "Marta S., direttrice marketing",
      stats: [{ label: "Recensioni Trustpilot", value: "289" }, { label: "Media", value: "4,7★" }, { label: "Conversione web", value: "+22%" }],
    },
    {
      Icon: Stethoscope, color: "from-purple-50 to-violet-50", accent: "text-purple-600",
      sector: "Salute", platform: "Google Maps",
      name: "Studio Dentistico Rossi", location: "Firenze",
      challenge: "Settore sensibile: volevano raccogliere opinioni positive naturalmente, ma temevano che i casi difficili finissero in recensioni negative pubbliche.",
      solution: "Il filtro di sentiment dell'IA è stato fondamentale. Solo i pazienti con risposte chiaramente positive ricevevano il link a Google Maps. Gli altri ricevevano un messaggio empatico per chiamare direttamente.",
      result: "62 nuove recensioni in 4 mesi, tutte sopra le 4 stelle. Nessuna risposta negativa è stata pubblicata — tutte gestite in privato.",
      quote: "Quello che apprezziamo di più non sono le nuove recensioni, ma che nessuna negativa sia stata pubblicata.",
      quoteName: "Dott. Rossi, proprietario",
      stats: [{ label: "Nuove recensioni", value: "+62" }, { label: "Recensioni negative pubbliche", value: "0" }, { label: "Soddisfazione", value: "94%" }],
    },
    {
      Icon: Smartphone, color: "from-rose-50 to-pink-50", accent: "text-rose-600",
      sector: "App mobile", platform: "App Store + Play Store",
      name: "RicettaApp", location: "Bologna",
      challenge: "18.000 utenti attivi mensili ma solo 312 valutazioni totali. Il basso rapporto penalizzava il ranking e rallentava i download organici.",
      solution: "Hanno segmentato gli utenti per dispositivo: iOS riceveva il link App Store, Android il link Play Store. Il messaggio veniva inviato agli utenti che avevano aperto l'app almeno 5 volte nell'ultimo mese.",
      result: "In 3 mesi +520 valutazioni su entrambe le piattaforme. La loro posizione nella categoria Gastronomia è passata dalla top 40 alla top 10, con il 35% in più di download organici.",
      quote: "Segmentare per dispositivo è stato geniale. Ogni utente riceveva esattamente il link giusto. Il tasso di risposta era del 28%.",
      quoteName: "Alex R., fondatore",
      stats: [{ label: "Nuove valutazioni", value: "+520" }, { label: "Piattaforme", value: "2" }, { label: "Posizione", value: "Top 10" }],
    },
    {
      Icon: Coffee, color: "from-yellow-50 to-orange-50", accent: "text-yellow-700",
      sector: "Caffè", platform: "Google Maps + Incentivo",
      name: "Caffè dei Fiori", location: "Venezia",
      challenge: "31 recensioni e 4,2★ mentre il concorrente di fronte aveva 180 recensioni e 4,8★. Sempre secondi. I clienti abituali li adoravano ma non lo dicevano mai su Google.",
      solution: "Hanno lanciato l'incentivo definitivo: lascia una recensione 5★, invia lo screenshot e ti offriamo un caffè. L'IA verificava automaticamente e inviava la conferma all'istante.",
      result: "Da 31 a 97 recensioni in 3 settimane e media di 4,8★. Hanno superato la concorrenza e appaiono ora primi per 'caffè Venezia centro'.",
      quote: "In 3 settimane avevamo più recensioni del concorrente che era lì da anni. Il caffè omaggio ci costava 50 centesimi e portava nuovi clienti.",
      quoteName: "Anna C., proprietaria",
      stats: [{ label: "Nuove recensioni", value: "+66" }, { label: "Media Google", value: "4,8★" }, { label: "Tempo", value: "3 settimane" }],
    },
    {
      Icon: Building2, color: "from-teal-50 to-cyan-50", accent: "text-teal-600",
      sector: "Ospitalità", platform: "Google Business Profile",
      name: "Hotel Belvedere", location: "Napoli",
      challenge: "Con una media di 4,2★ e diverse recensioni da 1 stella senza testo né storico utente, sospettavano recensioni false di un concorrente. Quelle 4 recensioni abbassavano la media e costavano prenotazioni dirette.",
      solution: "Con l'integrazione di Google Business Profile di ResenasYa, il sistema ha analizzato automaticamente le recensioni negative e identificato 4 che violavano le politiche di Google: senza commento, profili senza storico e contenuto generico. Hanno richiesto la rimozione con un clic.",
      result: "Google ha rimosso 3 delle 4 recensioni in 12 giorni. La media è passata da 4,2★ a 4,6★ e hanno recuperato 3 posizioni nel ranking locale degli hotel. Le prenotazioni dirette sono aumentate del 18% in quel trimestre.",
      quote: "Per mesi abbiamo visto quelle recensioni ingiuste affondarci. In 12 giorni Google ne ha rimosse 3 su 4. È stato un cambiamento enorme per la nostra reputazione.",
      quoteName: "Carlos V., direttore",
      stats: [{ label: "Recensioni rimosse", value: "3 su 4" }, { label: "Media Google", value: "4,6★" }, { label: "Prenotazioni dirette", value: "+18%" }],
    },
    {
      Icon: Sparkles, color: "from-violet-50 to-purple-50", accent: "text-violet-600",
      sector: "Benessere", platform: "Google Business Profile",
      name: "Spa Serenità", location: "Firenze",
      challenge: "Ricevevano 15 nuove recensioni a settimana su Google Maps ma rispondevano solo all'8%: non c'era tempo. Google penalizza i profili che non rispondono e loro lo sentivano nel ranking.",
      solution: "Hanno collegato Google Business Profile a ResenasYa. L'IA genera risposte personalizzate per ogni recensione tenendo conto del commento specifico del cliente e del tono dell'attività. Le risposte vengono pubblicate automaticamente in meno di un'ora.",
      result: "In 2 mesi il tasso di risposta è passato dall'8% al 94%. Google li ha etichettati come 'Risponde di solito' nella scheda. Sono saliti 4 posizioni nelle ricerche 'spa Firenze' e i clic sul profilo sono aumentati del 31%.",
      quote: "Prima impiegavamo giorni a rispondere e molte rimanevano senza risposta. Ora tutte hanno una risposta personalizzata in meno di un'ora. I clienti lo notano e lo apprezzano.",
      quoteName: "Elena R., direttrice",
      stats: [{ label: "Tasso di risposta", value: "94%" }, { label: "Tempo di risposta", value: "<1 ora" }, { label: "Clic sul profilo", value: "+31%" }],
    },
  ],

  pt: [
    {
      Icon: Utensils, color: "from-orange-50 to-amber-50", accent: "text-orange-600",
      sector: "Restauração", platform: "Google Maps",
      name: "Pizzaria Nápoles", location: "Lisboa",
      challenge: "23 avaliações em 2 anos. Só chegavam em momentos de reclamação. A média de 3,8★ tornava-os invisíveis nas pesquisas locais.",
      solution: "Implementaram o ResenasYa para enviar um WhatsApp automático 30 minutos após o pagamento. A IA filtrava as respostas: os satisfeitos recebiam o link do Google Maps, os insatisfeitos uma resposta empática.",
      result: "Em 2 meses passaram de 23 para 97 avaliações com uma média de 4,7★. Apareceram no top 3 dos restaurantes italianos em Lisboa e encheram a lista de espera aos fins de semana.",
      quote: "Ninguém deixava avaliações mesmo estando contente. Agora chegam sozinhas. Mudou completamente como nos veem no Google.",
      quoteName: "Giuseppe M., proprietário",
      stats: [{ label: "Novas avaliações", value: "+74" }, { label: "Média Google", value: "4,7★" }, { label: "Tempo", value: "2 meses" }],
    },
    {
      Icon: Dumbbell, color: "from-blue-50 to-indigo-50", accent: "text-blue-600",
      sector: "Fitness", platform: "Google Maps + Incentivo",
      name: "FitClub Gym", location: "Porto",
      challenge: "58 avaliações em 4 anos com NPS de 72. Os sócios estavam satisfeitos mas ninguém deixava avaliações. Pedir pessoalmente era constrangedor e pouco escalável.",
      solution: "Ativaram o plano Pro com incentivos: qualquer sócio que deixasse uma avaliação de 5★ e enviasse a captura de ecrã recebia 10% de desconto na próxima mensalidade. A IA verificava automaticamente e enviava o código de imediato.",
      result: "Em apenas 6 semanas obtiveram 134 novas avaliações com média de 4,9★. 62% dos sócios que receberam o WhatsApp com incentivo deixaram a avaliação.",
      quote: "O sistema de incentivos foi uma revelação. Os sócios viam-no como win-win: avaliação honesta em troca de desconto real. Sem fricção.",
      quoteName: "Laura P., diretora",
      stats: [{ label: "Novas avaliações", value: "+134" }, { label: "Média Google", value: "4,9★" }, { label: "Conv. incentivo", value: "62%" }],
    },
    {
      Icon: ShoppingBag, color: "from-green-50 to-emerald-50", accent: "text-green-600",
      sector: "E-commerce", platform: "Trustpilot",
      name: "ModaPortugal", location: "Braga",
      challenge: "Alta satisfação (NPS 78) mas zero presença no Trustpilot — onde os compradores tomavam a decisão final. Os concorrentes tinham centenas de avaliações, eles apenas 12.",
      solution: "Configuraram um WhatsApp automático 48 horas após a entrega. O link apontava diretamente para o perfil Trustpilot.",
      result: "Em 4 meses acumularam 289 avaliações com 4,7★ no Trustpilot. A taxa de conversão da loja online subiu 22%.",
      quote: "O impacto na conversão foi imediato. Quando os visitantes veem 289 avaliações reais de 4,7★, a decisão de compra toma-se sozinha.",
      quoteName: "Marta S., diretora de marketing",
      stats: [{ label: "Avaliações Trustpilot", value: "289" }, { label: "Média", value: "4,7★" }, { label: "Conversão web", value: "+22%" }],
    },
    {
      Icon: Stethoscope, color: "from-purple-50 to-violet-50", accent: "text-purple-600",
      sector: "Saúde", platform: "Google Maps",
      name: "Clínica Dentária Silva", location: "Coimbra",
      challenge: "Setor sensível: queriam recolher opiniões positivas naturalmente, mas temiam que casos difíceis acabassem em avaliações negativas públicas.",
      solution: "O filtro de sentimento da IA foi fundamental. Apenas os pacientes com respostas claramente positivas recebiam o link do Google Maps. Os outros recebiam uma mensagem empática para ligar diretamente.",
      result: "62 novas avaliações em 4 meses, todas acima de 4 estrelas. Nenhuma resposta negativa foi publicada — todas geridas em privado.",
      quote: "O que mais valorizamos não são as novas avaliações, mas que nenhuma negativa foi publicada.",
      quoteName: "Dra. Silva, proprietária",
      stats: [{ label: "Novas avaliações", value: "+62" }, { label: "Avaliações neg. públicas", value: "0" }, { label: "Satisfação", value: "94%" }],
    },
    {
      Icon: Smartphone, color: "from-rose-50 to-pink-50", accent: "text-rose-600",
      sector: "App móvel", platform: "App Store + Play Store",
      name: "ReceitaApp", location: "Setúbal",
      challenge: "18.000 utilizadores ativos mensais mas apenas 312 avaliações no total. O baixo rácio prejudicava o ranking e travava os downloads orgânicos.",
      solution: "Segmentaram por dispositivo: iOS recebia o link App Store, Android o link Play Store. A mensagem era enviada a utilizadores que tinham aberto a app pelo menos 5 vezes no último mês.",
      result: "Em 3 meses +520 avaliações nas duas plataformas. A sua posição na categoria Gastronomia subiu do top 40 para o top 10, com 35% mais downloads orgânicos.",
      quote: "Segmentar por dispositivo foi brilhante. Cada utilizador recebia exatamente o link certo. A taxa de resposta foi de 28%.",
      quoteName: "Alex R., fundador",
      stats: [{ label: "Novas avaliações", value: "+520" }, { label: "Plataformas", value: "2" }, { label: "Posição", value: "Top 10" }],
    },
    {
      Icon: Coffee, color: "from-yellow-50 to-orange-50", accent: "text-yellow-700",
      sector: "Café", platform: "Google Maps + Incentivo",
      name: "Café das Flores", location: "Aveiro",
      challenge: "31 avaliações e 4,2★ enquanto o concorrente em frente tinha 180 avaliações e 4,8★. Sempre em segundo lugar. Os habituais adoravam-nos mas nunca o punham no Google.",
      solution: "Lançaram o incentivo definitivo: deixa uma avaliação de 5★, envia a captura e oferecemos um café. A IA verificava automaticamente e enviava a confirmação de imediato.",
      result: "De 31 para 97 avaliações em 3 semanas e média de 4,8★. Ultrapassaram a concorrência e aparecem agora em primeiro nas pesquisas de 'café Aveiro centro'.",
      quote: "Em 3 semanas tínhamos mais avaliações do que o concorrente que estava lá há anos. O café de cortesia custava-nos 50 cêntimos e trouxe novos clientes.",
      quoteName: "Ana C., proprietária",
      stats: [{ label: "Novas avaliações", value: "+66" }, { label: "Média Google", value: "4,8★" }, { label: "Tempo", value: "3 semanas" }],
    },
    {
      Icon: Building2, color: "from-teal-50 to-cyan-50", accent: "text-teal-600",
      sector: "Hotelaria", platform: "Google Business Profile",
      name: "Hotel Miradouro", location: "Faro",
      challenge: "Com uma média de 4,2★ e várias avaliações de 1 estrela sem texto nem histórico de utilizador, suspeitavam de avaliações falsas de um concorrente. Essas 4 avaliações estavam a baixar a média e a custarem reservas diretas.",
      solution: "Com a integração do Google Business Profile do ResenasYa, o sistema analisou automaticamente as avaliações negativas e identificou 4 que violavam as políticas do Google: sem comentário, perfis sem histórico e conteúdo genérico. Solicitaram a remoção com um clique.",
      result: "O Google removeu 3 das 4 avaliações em 12 dias. A média subiu de 4,2★ para 4,6★ e recuperaram 3 posições no ranking local de hotéis. As reservas diretas aumentaram 18% nesse trimestre.",
      quote: "Durante meses vimos essas avaliações injustas a afundar-nos. Em 12 dias o Google removeu 3 de 4. Foi uma mudança brutal para a nossa reputação.",
      quoteName: "Carlos V., diretor",
      stats: [{ label: "Avaliações removidas", value: "3 de 4" }, { label: "Média Google", value: "4,6★" }, { label: "Reservas diretas", value: "+18%" }],
    },
    {
      Icon: Sparkles, color: "from-violet-50 to-purple-50", accent: "text-violet-600",
      sector: "Bem-estar", platform: "Google Business Profile",
      name: "Spa Serenidade", location: "Cascais",
      challenge: "Recebiam 15 novas avaliações por semana no Google Maps mas só respondiam a 8%: não havia tempo. O Google penaliza perfis que não respondem e eles sentiam-no no ranking.",
      solution: "Ligaram o Google Business Profile ao ResenasYa. A IA gera respostas personalizadas para cada avaliação tendo em conta o comentário específico do cliente e o tom do negócio. As respostas são publicadas automaticamente em menos de uma hora.",
      result: "Em 2 meses a taxa de resposta passou de 8% para 94%. O Google marcou-os como 'Responde habitualmente' na ficha. Subiram 4 posições nas pesquisas de 'spa Cascais' e os cliques no perfil aumentaram 31%.",
      quote: "Antes demorámos dias a responder e muitas ficavam sem resposta. Agora todas têm uma resposta personalizada em menos de uma hora. Os clientes notam e agradecem.",
      quoteName: "Elena R., diretora",
      stats: [{ label: "Taxa de resposta", value: "94%" }, { label: "Tempo de resposta", value: "<1 hora" }, { label: "Cliques no perfil", value: "+31%" }],
    },
  ],
};

export function getCaseStudies(locale: string): CaseStudyItem[] {
  return CASE_STUDIES[locale] ?? CASE_STUDIES["en"];
}
